version: 2
updates:
  # --- GitHub Actions ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # --- Bun ---
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      bun-dependencies:
        patterns: [ "*" ]
        update-types: [ "minor", "patch" ]
    ignore:
      - dependency-name: "typescript"
        update-types: [ "version-update:semver-major" ]
